// src/countries.rs - World Countries for CrimeBank Directory Structure

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Country {
    pub code: String,
    pub name: String,
}

/// Get all countries for directory initialization
pub fn get_all_countries() -> Vec<Country> {
    vec![
        // Africa
        Country { code: "DZ".to_string(), name: "Algeria".to_string() },
        Country { code: "AO".to_string(), name: "Angola".to_string() },
        Country { code: "BJ".to_string(), name: "Benin".to_string() },
        Country { code: "BW".to_string(), name: "Botswana".to_string() },
        Country { code: "BF".to_string(), name: "Burkina Faso".to_string() },
        Country { code: "BI".to_string(), name: "Burundi".to_string() },
        Country { code: "CM".to_string(), name: "Cameroon".to_string() },
        Country { code: "CV".to_string(), name: "Cape Verde".to_string() },
        Country { code: "CF".to_string(), name: "Central African Republic".to_string() },
        Country { code: "TD".to_string(), name: "Chad".to_string() },
        Country { code: "KM".to_string(), name: "Comoros".to_string() },
        Country { code: "CG".to_string(), name: "Congo".to_string() },
        Country { code: "CD".to_string(), name: "Democratic Republic of the Congo".to_string() },
        Country { code: "CI".to_string(), name: "Cote d'Ivoire".to_string() },
        Country { code: "DJ".to_string(), name: "Djibouti".to_string() },
        Country { code: "EG".to_string(), name: "Egypt".to_string() },
        Country { code: "GQ".to_string(), name: "Equatorial Guinea".to_string() },
        Country { code: "ER".to_string(), name: "Eritrea".to_string() },
        Country { code: "ET".to_string(), name: "Ethiopia".to_string() },
        Country { code: "GA".to_string(), name: "Gabon".to_string() },
        Country { code: "GM".to_string(), name: "Gambia".to_string() },
        Country { code: "GH".to_string(), name: "Ghana".to_string() },
        Country { code: "GN".to_string(), name: "Guinea".to_string() },
        Country { code: "GW".to_string(), name: "Guinea-Bissau".to_string() },
        Country { code: "KE".to_string(), name: "Kenya".to_string() },
        Country { code: "LS".to_string(), name: "Lesotho".to_string() },
        Country { code: "LR".to_string(), name: "Liberia".to_string() },
        Country { code: "LY".to_string(), name: "Libya".to_string() },
        Country { code: "MG".to_string(), name: "Madagascar".to_string() },
        Country { code: "MW".to_string(), name: "Malawi".to_string() },
        Country { code: "ML".to_string(), name: "Mali".to_string() },
        Country { code: "MR".to_string(), name: "Mauritania".to_string() },
        Country { code: "MU".to_string(), name: "Mauritius".to_string() },
        Country { code: "MA".to_string(), name: "Morocco".to_string() },
        Country { code: "MZ".to_string(), name: "Mozambique".to_string() },
        Country { code: "NA".to_string(), name: "Namibia".to_string() },
        Country { code: "NE".to_string(), name: "Niger".to_string() },
        Country { code: "NG".to_string(), name: "Nigeria".to_string() },
        Country { code: "RW".to_string(), name: "Rwanda".to_string() },
        Country { code: "ST".to_string(), name: "Sao Tome and Principe".to_string() },
        Country { code: "SN".to_string(), name: "Senegal".to_string() },
        Country { code: "SC".to_string(), name: "Seychelles".to_string() },
        Country { code: "SL".to_string(), name: "Sierra Leone".to_string() },
        Country { code: "SO".to_string(), name: "Somalia".to_string() },
        Country { code: "ZA".to_string(), name: "South Africa".to_string() },
        Country { code: "SS".to_string(), name: "South Sudan".to_string() },
        Country { code: "SD".to_string(), name: "Sudan".to_string() },
        Country { code: "SZ".to_string(), name: "Swaziland".to_string() },
        Country { code: "TZ".to_string(), name: "Tanzania".to_string() },
        Country { code: "TG".to_string(), name: "Togo".to_string() },
        Country { code: "TN".to_string(), name: "Tunisia".to_string() },
        Country { code: "UG".to_string(), name: "Uganda".to_string() },
        Country { code: "ZM".to_string(), name: "Zambia".to_string() },
        Country { code: "ZW".to_string(), name: "Zimbabwe".to_string() },
        
        // Asia
        Country { code: "AF".to_string(), name: "Afghanistan".to_string() },
        Country { code: "AM".to_string(), name: "Armenia".to_string() },
        Country { code: "AZ".to_string(), name: "Azerbaijan".to_string() },
        Country { code: "BH".to_string(), name: "Bahrain".to_string() },
        Country { code: "BD".to_string(), name: "Bangladesh".to_string() },
        Country { code: "BT".to_string(), name: "Bhutan".to_string() },
        Country { code: "BN".to_string(), name: "Brunei".to_string() },
        Country { code: "KH".to_string(), name: "Cambodia".to_string() },
        Country { code: "CN".to_string(), name: "China".to_string() },
        Country { code: "GE".to_string(), name: "Georgia".to_string() },
        Country { code: "IN".to_string(), name: "India".to_string() },
        Country { code: "ID".to_string(), name: "Indonesia".to_string() },
        Country { code: "IR".to_string(), name: "Iran".to_string() },
        Country { code: "IQ".to_string(), name: "Iraq".to_string() },
        Country { code: "IL".to_string(), name: "Israel".to_string() },
        Country { code: "JP".to_string(), name: "Japan".to_string() },
        Country { code: "JO".to_string(), name: "Jordan".to_string() },
        Country { code: "KZ".to_string(), name: "Kazakhstan".to_string() },
        Country { code: "KW".to_string(), name: "Kuwait".to_string() },
        Country { code: "KG".to_string(), name: "Kyrgyzstan".to_string() },
        Country { code: "LA".to_string(), name: "Laos".to_string() },
        Country { code: "LB".to_string(), name: "Lebanon".to_string() },
        Country { code: "MY".to_string(), name: "Malaysia".to_string() },
        Country { code: "MV".to_string(), name: "Maldives".to_string() },
        Country { code: "MN".to_string(), name: "Mongolia".to_string() },
        Country { code: "MM".to_string(), name: "Myanmar".to_string() },
        Country { code: "NP".to_string(), name: "Nepal".to_string() },
        Country { code: "KP".to_string(), name: "North Korea".to_string() },
        Country { code: "OM".to_string(), name: "Oman".to_string() },
        Country { code: "PK".to_string(), name: "Pakistan".to_string() },
        Country { code: "PS".to_string(), name: "Palestine".to_string() },
        Country { code: "PH".to_string(), name: "Philippines".to_string() },
        Country { code: "QA".to_string(), name: "Qatar".to_string() },
        Country { code: "SA".to_string(), name: "Saudi Arabia".to_string() },
        Country { code: "SG".to_string(), name: "Singapore".to_string() },
        Country { code: "KR".to_string(), name: "South Korea".to_string() },
        Country { code: "LK".to_string(), name: "Sri Lanka".to_string() },
        Country { code: "SY".to_string(), name: "Syria".to_string() },
        Country { code: "TW".to_string(), name: "Taiwan".to_string() },
        Country { code: "TJ".to_string(), name: "Tajikistan".to_string() },
        Country { code: "TH".to_string(), name: "Thailand".to_string() },
        Country { code: "TL".to_string(), name: "Timor-Leste".to_string() },
        Country { code: "TR".to_string(), name: "Turkey".to_string() },
        Country { code: "TM".to_string(), name: "Turkmenistan".to_string() },
        Country { code: "AE".to_string(), name: "United Arab Emirates".to_string() },
        Country { code: "UZ".to_string(), name: "Uzbekistan".to_string() },
        Country { code: "VN".to_string(), name: "Vietnam".to_string() },
        Country { code: "YE".to_string(), name: "Yemen".to_string() },
        
        // Europe
        Country { code: "AL".to_string(), name: "Albania".to_string() },
        Country { code: "AD".to_string(), name: "Andorra".to_string() },
        Country { code: "AT".to_string(), name: "Austria".to_string() },
        Country { code: "BY".to_string(), name: "Belarus".to_string() },
        Country { code: "BE".to_string(), name: "Belgium".to_string() },
        Country { code: "BA".to_string(), name: "Bosnia and Herzegovina".to_string() },
        Country { code: "BG".to_string(), name: "Bulgaria".to_string() },
        Country { code: "HR".to_string(), name: "Croatia".to_string() },
        Country { code: "CY".to_string(), name: "Cyprus".to_string() },
        Country { code: "CZ".to_string(), name: "Czech Republic".to_string() },
        Country { code: "DK".to_string(), name: "Denmark".to_string() },
        Country { code: "EE".to_string(), name: "Estonia".to_string() },
        Country { code: "FI".to_string(), name: "Finland".to_string() },
        Country { code: "FR".to_string(), name: "France".to_string() },
        Country { code: "DE".to_string(), name: "Germany".to_string() },
        Country { code: "GR".to_string(), name: "Greece".to_string() },
        Country { code: "HU".to_string(), name: "Hungary".to_string() },
        Country { code: "IS".to_string(), name: "Iceland".to_string() },
        Country { code: "IE".to_string(), name: "Ireland".to_string() },
        Country { code: "IT".to_string(), name: "Italy".to_string() },
        Country { code: "XK".to_string(), name: "Kosovo".to_string() },
        Country { code: "LV".to_string(), name: "Latvia".to_string() },
        Country { code: "LI".to_string(), name: "Liechtenstein".to_string() },
        Country { code: "LT".to_string(), name: "Lithuania".to_string() },
        Country { code: "LU".to_string(), name: "Luxembourg".to_string() },
        Country { code: "MK".to_string(), name: "Macedonia".to_string() },
        Country { code: "MT".to_string(), name: "Malta".to_string() },
        Country { code: "MD".to_string(), name: "Moldova".to_string() },
        Country { code: "MC".to_string(), name: "Monaco".to_string() },
        Country { code: "ME".to_string(), name: "Montenegro".to_string() },
        Country { code: "NL".to_string(), name: "Netherlands".to_string() },
        Country { code: "NO".to_string(), name: "Norway".to_string() },
        Country { code: "PL".to_string(), name: "Poland".to_string() },
        Country { code: "PT".to_string(), name: "Portugal".to_string() },
        Country { code: "RO".to_string(), name: "Romania".to_string() },
        Country { code: "RU".to_string(), name: "Russia".to_string() },
        Country { code: "SM".to_string(), name: "San Marino".to_string() },
        Country { code: "RS".to_string(), name: "Serbia".to_string() },
        Country { code: "SK".to_string(), name: "Slovakia".to_string() },
        Country { code: "SI".to_string(), name: "Slovenia".to_string() },
        Country { code: "ES".to_string(), name: "Spain".to_string() },
        Country { code: "SE".to_string(), name: "Sweden".to_string() },
        Country { code: "CH".to_string(), name: "Switzerland".to_string() },
        Country { code: "UA".to_string(), name: "Ukraine".to_string() },
        Country { code: "GB".to_string(), name: "United Kingdom".to_string() },
        Country { code: "VA".to_string(), name: "Vatican City".to_string() },
        
        // North America
        Country { code: "AG".to_string(), name: "Antigua and Barbuda".to_string() },
        Country { code: "BS".to_string(), name: "Bahamas".to_string() },
        Country { code: "BB".to_string(), name: "Barbados".to_string() },
        Country { code: "BZ".to_string(), name: "Belize".to_string() },
        Country { code: "CA".to_string(), name: "Canada".to_string() },
        Country { code: "CR".to_string(), name: "Costa Rica".to_string() },
        Country { code: "CU".to_string(), name: "Cuba".to_string() },
        Country { code: "DM".to_string(), name: "Dominica".to_string() },
        Country { code: "DO".to_string(), name: "Dominican Republic".to_string() },
        Country { code: "SV".to_string(), name: "El Salvador".to_string() },
        Country { code: "GD".to_string(), name: "Grenada".to_string() },
        Country { code: "GT".to_string(), name: "Guatemala".to_string() },
        Country { code: "HT".to_string(), name: "Haiti".to_string() },
        Country { code: "HN".to_string(), name: "Honduras".to_string() },
        Country { code: "JM".to_string(), name: "Jamaica".to_string() },
        Country { code: "MX".to_string(), name: "Mexico".to_string() },
        Country { code: "NI".to_string(), name: "Nicaragua".to_string() },
        Country { code: "PA".to_string(), name: "Panama".to_string() },
        Country { code: "KN".to_string(), name: "Saint Kitts and Nevis".to_string() },
        Country { code: "LC".to_string(), name: "Saint Lucia".to_string() },
        Country { code: "VC".to_string(), name: "Saint Vincent and the Grenadines".to_string() },
        Country { code: "TT".to_string(), name: "Trinidad and Tobago".to_string() },
        Country { code: "US".to_string(), name: "United States".to_string() },
        
        // South America
        Country { code: "AR".to_string(), name: "Argentina".to_string() },
        Country { code: "BO".to_string(), name: "Bolivia".to_string() },
        Country { code: "BR".to_string(), name: "Brazil".to_string() },
        Country { code: "CL".to_string(), name: "Chile".to_string() },
        Country { code: "CO".to_string(), name: "Colombia".to_string() },
        Country { code: "EC".to_string(), name: "Ecuador".to_string() },
        Country { code: "GY".to_string(), name: "Guyana".to_string() },
        Country { code: "PY".to_string(), name: "Paraguay".to_string() },
        Country { code: "PE".to_string(), name: "Peru".to_string() },
        Country { code: "SR".to_string(), name: "Suriname".to_string() },
        Country { code: "UY".to_string(), name: "Uruguay".to_string() },
        Country { code: "VE".to_string(), name: "Venezuela".to_string() },
        
        // Oceania
        Country { code: "AU".to_string(), name: "Australia".to_string() },
        Country { code: "FJ".to_string(), name: "Fiji".to_string() },
        Country { code: "KI".to_string(), name: "Kiribati".to_string() },
        Country { code: "MH".to_string(), name: "Marshall Islands".to_string() },
        Country { code: "FM".to_string(), name: "Micronesia".to_string() },
        Country { code: "NR".to_string(), name: "Nauru".to_string() },
        Country { code: "NZ".to_string(), name: "New Zealand".to_string() },
        Country { code: "PW".to_string(), name: "Palau".to_string() },
        Country { code: "PG".to_string(), name: "Papua New Guinea".to_string() },
        Country { code: "WS".to_string(), name: "Samoa".to_string() },
        Country { code: "SB".to_string(), name: "Solomon Islands".to_string() },
        Country { code: "TO".to_string(), name: "Tonga".to_string() },
        Country { code: "TV".to_string(), name: "Tuvalu".to_string() },
        Country { code: "VU".to_string(), name: "Vanuatu".to_string() },
    ]
}

/// Get country name from country code
pub fn get_country_name(code: &str) -> Option<String> {
    get_all_countries()
        .into_iter()
        .find(|c| c.code.eq_ignore_ascii_case(code))
        .map(|c| c.name)
}

/// Get country code from country name
pub fn get_country_code(name: &str) -> Option<String> {
    get_all_countries()
        .into_iter()
        .find(|c| c.name.eq_ignore_ascii_case(name))
        .map(|c| c.code)
}

/// Normalize country name (for directory naming)
pub fn normalize_country_name(name: &str) -> String {
    name.replace(" ", "_")
        .replace("'", "")
        .replace(".", "")
}